### PR TITLE
Adds a Send() method

### PR DESCRIPTION
**Pull request by diamondburned**
This method asserts multiple types before falling back to Reply(), as I felt like this should be Send()'s proper behavior.

### CODE REVIEW

**Comment by Necroforger** [comment]
I think it would be better to instead create a ReplyComplex method to handle the MessageSend struct.

**Comment by diamondburned** [comment]
I don't get what the point of Reply() is then? Apparently it takes in an `interface{}` and passes that to `Sprint`, though I'm not sure what the point of that is?

**Comment by Necroforger** [comment]
> 
> 
> I don't get what the point of Reply() is then? Apparently it takes in an `interface{}` and passes that to `Sprint`, though I'm not sure what the point of that is?

It is for sending things that implement the Stringer interface. For example, if you wanted to send an error you could use `Reply("Something went wrong", err)`. 

I wouldn't be against adding a type switch on the first argument to change the behavior.

```go
if (len(args) != 0) {
   switch t := args[0].(type) {
   case *discordgo.MessageSend:
       return s.ChannelMessageSendComplex( // ...
   case *discordgo.MessageEmbed:
       return s.ChannelMessageSendEmbed( // ...
   }
}
return s.ChannelMessageSend( fmt.Sprint( args ... ) )
```

**Comment by wooptroop** [comment]
Any reason why this PR isn't merged yet? I would love to be able to send an embed; not as just a description but as a full-featured embed. Is there already a way to do this?

**Pull request closed without merging**
